### ISSUE TITLE
Got Skypack dependency issue.

### ISSUE THREAD

**Issue by iksflow** [slack-samples/deno-announcement-bot#48]
Hello, I'm trying to start a Slack app, but I encountered the following Skypack error. 
How can I resolve this?

```sh
$ slack run
# ...Choose a local environment...

error: Uncaught (in promise) TypeError: Requires import access to "cdn.skypack.dev:443", run again with the --allow-import flag
    at file:///Users/iksflow/slack-app/announcement-bot-app/functions/create_draft/blocks.ts:5:8
  const functionModule = await import(`file://${functionFilePath}`);
                         ^
    at async getDefaultExport (https://deno.land/x/deno_slack_hooks@1.3.0/utilities.ts:27:26)
    at async validateManifestFunctions (https://deno.land/x/deno_slack_hooks@1.3.0/utilities.ts:76:27)
    at async getValidateAndCleanManifest (https://deno.land/x/deno_slack_hooks@1.3.0/get_manifest.ts:130:3)
    at async https://deno.land/x/deno_slack_hooks@1.3.0/get_manifest.ts:136:26
```

**Comment by deividmarcinkevic** [comment]
Hey @iksflow, have you solved this issue, as I get the same error?

**Comment by deividmarcinkevic** [comment]
Hey @iksflow, you need to downgrade your deno version: deno upgrade --version 1.46.3
or brew uninstall deno ->  curl -fsSL https://deno.land/x/install/install.sh | sh -s v1.46.3

**Comment by zimeg** [comment]
👋 Apologies for this late response, and thanks for sharing this workaround @deividmarcinkevic!

We have efforts towards improved compatibilities being tracked now in this [issue](https://github.com/slackapi/deno-slack-sdk/issues/458). Let's keep **this** issue open for now to make sure this sample is in a working state soon though 🙏 ✨
